initial draft for github action
celery/py-amqp pull request #358
Opened 2021-02-25 13:17 UTC by auvipy

should not work now as expected as it's an early experiment. some changes are needed to work properly.

2021-02-28 06:47 UTC, auvipy commented
set_cloexec(self.sock, True)
                    except NotImplementedError:
                        pass
                    self.sock.settimeout(timeout)
>                   self.sock.connect(sa)
E                   ConnectionRefusedError: [Errno 111] Connection refused

amqp/transport.py:197: ConnectionRefusedError
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
==================== 1 failed, 33 passed, 5 rerun in 10.91s ====================

2021-02-28 10:29 UTC, thedrow requested changes

2021-02-28 10:29 UTC, thedrow commented on .github/workflows/workflow.yaml
> +        PYTHONPATH=. pytest -xv --cov=celery --cov-report=xml --cov-report term t/unit
Run with tox.

2021-02-28 10:29 UTC, thedrow commented on .github/workflows/workflow.yaml
> +        PYTHONPATH=. pytest -xv -E rabbitmq t/integration
This won't work without tox.

2021-03-05 04:00 UTC, auvipy commented on .github/workflows/workflow.yaml
> +        PYTHONPATH=. pytest -xv -E rabbitmq t/integration
ok

2026-09-07 07:47 UTC, closed without merging