improve performance of _get_free_channel_id, fix channel max bug
celery/py-amqp pull request #385
Opened 2021-12-21 05:14 UTC by pawl

This PR fixes a performance issue introduced by #377.

I noticed while running tests that `_get_free_channel_id` is way slower than I expected.

Surprisingly, this code that's similar to `_get_free_channel_id` (when all the channel ids are used) takes almost 40 seconds to run:
```
import time
from array import array

channel_max = 65535
used_channel_ids = array('H', range(1, channel_max + 1))
start = time.time()
for channel_id in range(1, channel_max + 1):
    if channel_id not in used_channel_ids:
        assert False
print(f'finished {time.time() - start:0.3f}')
```

This PR casts `_used_channel_ids` to a `set` before the loop, and it only takes ~0.004 seconds to run the loop after this change. It also allows keeping the memory usage improvements by keeping the `_used_channel_ids` stored as an array on the class.

I also learned that there's a bug preventing `_get_free_channel_id` from reaching the `channel_max` (the limit is currently channel_max - 1), and I fixed that too.

2021-12-21 05:41 UTC, auvipy requested changes
can you also adjust some integration tests as well?

2021-12-21 06:10 UTC, pawl commented
@auvipy Is this what you were thinking?: https://github.com/celery/py-amqp/pull/385/commits/3db6df1b35f1cc4f213ed6d5f4e461c89d00c48e

2021-12-21 09:10 UTC, auvipy commented
yes

2021-12-22 11:16 UTC, auvipy approved these changes

2021-12-22 11:17 UTC, merged

2022-02-02 21:56 UTC, skinnyh commented
Hi, can we get a version bump for this fix? Thank you!

2022-02-03 02:53 UTC, auvipy commented
Yes of course, this weekend for sure

2022-02-14 20:15 UTC, skinnyh commented
> Yes of course, this weekend for sure

Hi, any update on it?

2022-04-24 11:18 UTC, GuardianRain commented
Hi, which version has already include this fix? Thank you!

2022-04-24 14:46 UTC, auvipy commented
5.1.1 please